version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodbresale
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - revenda

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongo:27017/resale?authSource=admin
      - SPRING_DATA_MONGODB_URI_TEST=mongodb://root:root@localhost:27017/resale_test?authSource=admin
    depends_on:
      - mongo
    networks:
      - revenda

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - revenda
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - revenda

volumes:
  mongo-data:
    driver: local
networks:
  revenda:
    driver: bridge